//
// Created by babay on 22.05.2018.
//

#ifndef PROVER_MVP_ANDROID_SETTINGS_H
#define PROVER_MVP_ANDROID_SETTINGS_H

//#define RECT_DEFECT
#define DEFECT 0.1
#define DEFECT_CLIENT 0.1
#define MS_PER_SWIPE_STEP 2500
#define PAUSE_TO_ST3_MS_PER_STEP 300
#define SWYPE_SPEED 1.4

#define VECTOR_WINDOW_START 0.025
#define VECTOR_WINDOW_END 0.04

#define TARGET_RADIUS 0.16
#define DIAGONAL_TARGET_RADIUS_MULT 1.4

#define MIN_TIME_BETWEEN_DETECTORS 100

#endif //PROVER_MVP_ANDROID_SETTINGS_H
