# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!

target 'ProverSwipe' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PROVERClapperboard
  pod 'Moya'
  pod 'Result'
  pod 'Geth'
  pod 'KeychainSwift'
  pod 'FileBrowser'
  pod 'OpenCV'
  pod 'CryptoSwift'
  pod 'CoreStore'
  pod 'ObjectMapper'
  pod 'SwiftyJSON'

  target 'Tests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end
end
